openapi: 3.0.0
info:
  title: CMS API
  description: RESTful API for CMS built with CodeIgniter 4
  version: 1.0.0
  contact:
    name: API Support
    email: api@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080/api/v1
    description: Development server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

    ApiSecretAuth:
      type: apiKey
      in: header
      name: X-API-Secret

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time

    Media:
      type: object
      properties:
        id:
          type: integer
        filename:
          type: string
        url:
          type: string
        type:
          type: string
          enum: [image, video, audio, document, other]
        size:
          type: integer
        created_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string
        errors:
          type: object

    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
        total_pages:
          type: integer
        has_more:
          type: boolean

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                      token:
                        type: object
                        properties:
                          key:
                            type: string
                          secret:
                            type: string
                          expires_at:
                            type: string
                            format: date-time
        401:
          description: Invalid credentials

  /media:
    get:
      tags:
        - Media
      summary: Get media list
      security:
        - ApiKeyAuth: []
        - ApiSecretAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
        - name: type
          in: query
          schema:
            type: string
            enum: [image, video, audio, document, other]
        - name: folder
          in: query
          schema:
            type: string
      responses:
        200:
          description: Media list retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Media'
                  pagination:
                    $ref: '#/components/schemas/PaginationMeta'

    post:
      tags:
        - Media
      summary: Upload media file
      security:
        - ApiKeyAuth: []
        - ApiSecretAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                folder:
                  type: string
                alt_text:
                  type: string
                description:
                  type: string
                is_public:
                  type: boolean
                  default: true
      responses:
        201:
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Media'